// SPDX-License-Identifier: Unlicense OR MIT

//go:build ignore

// This program writes icons.go: the list of every icon of
// golang.org/x/exp/shiny/materialdesign/icons, which the package itself does
// not offer. It reads the package's source in the module cache, at the
// version go.mod requires.
package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"log"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

// categories are the groups of Material Design icons, the prefixes of their
// names.
var categories = []string{
	"Action", "Alert", "AV", "Communication", "Content", "Device", "Editor",
	"File", "Hardware", "Image", "Maps", "Navigation", "Notification",
	"Places", "Social", "Toggle",
}

func main() {
	out, err := exec.Command("go", "list", "-m", "-f", "{{.Dir}}", "golang.org/x/exp/shiny").Output()
	if err != nil {
		log.Fatalf("finding golang.org/x/exp/shiny: %v", err)
	}
	dir := filepath.Join(strings.TrimSpace(string(out)), "materialdesign", "icons")
	file, err := parser.ParseFile(token.NewFileSet(), filepath.Join(dir, "data.go"), nil, parser.SkipObjectResolution)
	if err != nil {
		log.Fatal(err)
	}

	var b bytes.Buffer
	b.WriteString(`// Code generated by go run gen.go; DO NOT EDIT.

package main

import "golang.org/x/exp/shiny/materialdesign/icons"

// allIcons is every icon of the icons package, in the order of its source:
// by category, then by name.
var allIcons = []icon{
`)
	count := 0
	for _, decl := range file.Decls {
		gen, ok := decl.(*ast.GenDecl)
		if !ok || gen.Tok != token.VAR {
			continue
		}
		for _, spec := range gen.Specs {
			for _, name := range spec.(*ast.ValueSpec).Names {
				category := categoryOf(name.Name)
				if category == "" {
					log.Fatalf("%s has no known category", name.Name)
				}
				fmt.Fprintf(&b, "\t{%q, %q, icons.%s},\n", category, name.Name, name.Name)
				count++
			}
		}
	}
	b.WriteString("}\n")

	src, err := format.Source(b.Bytes())
	if err != nil {
		log.Fatal(err)
	}
	if err := os.WriteFile("icons.go", src, 0o644); err != nil {
		log.Fatal(err)
	}
	log.Printf("wrote %d icons", count)
}

func categoryOf(name string) string {
	for _, c := range categories {
		// The next letter starts a new word, so that "Action" does not take
		// a name of a category that merely begins with it.
		if rest, ok := strings.CutPrefix(name, c); ok && rest != "" && (rest[0] < 'a' || rest[0] > 'z') {
			return c
		}
	}
	return ""
}
